#!/bin/bash
set -e

# 環境変数のデバッグ出力
echo "⭐️Environment variables:"
echo "Current directory: $(pwd)"
echo "CI: $CI"
echo "CCI_BUILD_ID: $CI_BUILD_ID"
echo "CI_BUILD_NUMBER: $CI_BUILD_NUMBER"
echo "CI_BUILD_URL: $CI_BUILD_URL"
echo "CI_BUNDLE_ID: $CI_BUNDLE_ID"
echo "CI_COMMIT: $CI_COMMIT"
echo "CI_DERIVED_DATA_PATH: $CI_DERIVED_DATA_PATH"
echo "CI_PRIMARY_REPOSITORY_PATH: $CI_PRIMARY_REPOSITORY_PATH"
echo "CI_PRODUCT: $CI_PRODUCT"
echo "CI_PRODUCT_ID: $CI_PRODUCT_ID"
echo "CI_PRODUCT_PLATFORM: $CI_PRODUCT_PLATFORM"
echo "CI_PROJECT_FILE_PATH: $CI_PROJECT_FILE_PATH"
echo "CI_START_CONDITION: $CI_START_CONDITION"
echo "CI_TEAM_ID: $CI_TEAM_ID"
echo "CI_WORKFLOW: $CI_WORKFLOW"
echo "CI_WORKFLOW_ID: $CI_WORKFLOW_ID"
echo "CI_WORKSPACE_PATH: $CI_WORKSPACE_PATH"
echo "CI_XCODE_CLOUD: $CI_XCODE_CLOUD"
echo "CI_XCODE_PROJECT: $CI_XCODE_PROJECT"
echo "CI_XCODE_SCHEME: $CI_XCODE_SCHEME"
echo "CI_XCODEBUILD_ACTION: $CI_XCODEBUILD_ACTION"
echo "CI_XCODEBUILD_EXIT_CODE: $CI_XCODEBUILD_EXIT_CODE"
echo "CI_BRANCH: $CI_BRANCH"
echo "CI_TAG: $CI_TAG"
echo "CI_GIT_REF: $CI_GIT_REF"
echo "CI_PULL_REQUEST_HTML_URL: $CI_PULL_REQUEST_HTML_URL"
echo "CI_PULL_REQUEST_NUMBER: $CI_PULL_REQUEST_NUMBER"
echo "CI_PULL_REQUEST_SOURCE_BRANCH: $CI_PULL_REQUEST_SOURCE_BRANCH"
echo "CI_PULL_REQUEST_SOURCE_COMMIT: $CI_PULL_REQUEST_SOURCE_COMMIT"
echo "CI_PULL_REQUEST_SOURCE_REPO: $CI_PULL_REQUEST_SOURCE_REPO"
echo "CI_PULL_REQUEST_TARGET_BRANCH: $CI_PULL_REQUEST_TARGET_BRANCH"
echo "CI_PULL_REQUEST_TARGET_COMMIT: $CI_PULL_REQUEST_TARGET_COMMIT"
echo "CI_PULL_REQUEST_TARGET_REPO: $CI_PULL_REQUEST_TARGET_REPO"

echo "CI_RESULT_BUNDLE_PATH: $CI_RESULT_BUNDLE_PATH"
echo "CI_TEST_DESTINATION_DEVICE_TYPE: $CI_TEST_DESTINATION_DEVICE_TYPE"
echo "CI_TEST_DESTINATION_RUNTIME: $CI_TEST_DESTINATION_RUNTIME"
echo "CI_TEST_DESTINATION_UDID: $CI_TEST_DESTINATION_UDID"
echo "CI_TEST_PLAN: $CI_TEST_PLAN"
echo "CI_TEST_PRODUCTS_PATH: $CI_TEST_PRODUCTS_PATH"

echo "CI_AD_HOC_SIGNED_APP_PATH: $CI_AD_HOC_SIGNED_APP_PATH"
echo "CI_APP_STORE_SIGNED_APP_PATH: $CI_APP_STORE_SIGNED_APP_PATH"
echo "CI_ARCHIVE_PATH: $CI_ARCHIVE_PATH"
echo "CI_DEVELOPMENT_SIGNED_APP_PATH: $CI_DEVELOPMENT_SIGNED_APP_PATH"
echo "CI_DEVELOPER_ID_SIGNED_APP_PATH: $CI_DEVELOPER_ID_SIGNED_APP_PATH"

# ディレクトリパス
BASE_DIR="/Volumes/workspace/repository"

# ディレクトリ構造を出力（findとlsを使用）
echo "🗂️ ディレクトリ構造:"
cd "$BASE_DIR"
find . -maxdepth 6 -type d | sort | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"

echo -e "\n\n📄 全ファイルリスト (相対パス):"
find . -type f | sort

echo -e "\n\n📊 ディレクトリとファイルのサマリ:"
echo "総ディレクトリ数:"
find . -type d | wc -l

echo "総ファイル数:"
find . -type f | wc -l

echo -e "\n\n🔍 ファイル拡張子の分布:"
find . -type f | sed -e 's/.*\.//' | sort | uniq -c | sort -rn

echo -e "\n\n📋 各ディレクトリの直下のファイルとサブディレクトリ:"
for dir in */; do
    echo -e "\n${dir}内容:"
    ls -1 "$dir"
done